import React from "react";
import type { Metadata } from "next";
import SideBar from "@/src/ui/SideBar/SideBar";
import { inter } from "@/src/styles/fonts";

export const metadata: Metadata = {
  title: "ArrowFlicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar />
        {children}
      </body>
    </html>
  );
}
